name: jasaku_by_roads
description: Aplikasi JASAKU By. Roads
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: 6.2.1  # Untuk fitur WhatsApp
  cupertino_icons: 1.0.6

flutter:
  uses-material-design: true
